theme = "blowfish"
baseURL = "https://yu-fu.site/"
canonifyURLs = true
defaultContentLanguage = "ja"

enableRobotsTXT = true
enableGitInfo = true
summaryLength = 30
hasCJKLanguage = true

[markup.goldmark.renderer]
  unsafe = true
[related]
  threshold = 1
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10

[frontmatter]
  lastmod = ["lastmod", "date", "publishDate"]

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 8

[imaging]
  anchor = 'Center'
  quality = 85
  resampleFilter = 'Box'
  [imaging.webp]
    quality = 85
    lossless = false

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    id = "G-GFGGCGQJQ2"
