[[main]]
  name = "ホーム"
  url = "/"
  weight = 10

[[main]]
  name = "記事一覧"
  url = "/posts/"
  weight = 15

[[main]]
  name = "運営者情報"
  url = "/about/"
  weight = 20

[[main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 30

[[footer]]
  name = "プライバシーポリシー"
  url = "/privacy/"
  weight = 10
